### ISSUE TITLE
Basic build method conversion error

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#167]
Decided to test out the basic build method for a node and I get a nil conversion error. Doing a build _before_ creating a config file for the node containing `build_method: basic` is fine. Output from trace below.
```
[root@controller tftpboot]# metal build node05 --trace
/opt/metalware/src/dependency.rb:113:in `join': no implicit conversion of nil into String (TypeError)
	from /opt/metalware/src/dependency.rb:113:in `valid_file?'
	from /opt/metalware/src/dependency.rb:59:in `validate_dependency_value'
	from /opt/metalware/src/dependency.rb:54:in `block (2 levels) in run_dependencies'
	from /opt/metalware/src/dependency.rb:54:in `each'
	from /opt/metalware/src/dependency.rb:54:in `block in run_dependencies'
	from /opt/metalware/src/dependency.rb:48:in `each'
	from /opt/metalware/src/dependency.rb:48:in `run_dependencies'
	from /opt/metalware/src/dependency.rb:39:in `enforce'
	from /opt/metalware/src/command_helpers/base_command.rb:77:in `enforce_dependency'
	from /opt/metalware/src/command_helpers/base_command.rb:57:in `post_setup'
	from /opt/metalware/src/command_helpers/base_command.rb:39:in `initialize'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `new'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `call'
	from /opt/metalware/src/commander_extensions.rb:61:in `call'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:184:in `run'
	from /opt/metalware/src/commander_extensions.rb:49:in `run'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:464:in `run_active_command'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:66:in `run!'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/delegates.rb:15:in `run!'
	from /opt/metalware/src/cli.rb:52:in `run!'
	from /opt/metalware/src/cli.rb:47:in `run'
	from bin/metal:28:in `<main>'
```

**Comment by bobwhitelock** [comment]
Thanks for the bug report; I see the issue, just working on a fix.
