### ISSUE TITLE
Metal repo use error

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#170]
The below error message appeared when doing a fresh install of metalware (tested with `develop` and `feature/named` branches).
```
[root@controller ~]# metal repo use https://github.com/alces-software/metalware-default.git
/opt/metalware/src/network.rb:9:in `singleton class': undefined method `delegate' for #<Class:Metalware::Network> (NoMethodError)
Did you mean?  DelegateClass
	from /opt/metalware/src/network.rb:8:in `<module:Network>'
	from /opt/metalware/src/network.rb:7:in `<module:Metalware>'
	from /opt/metalware/src/network.rb:6:in `<top (required)>'
	from /opt/metalware/src/domain_templates_renderer.rb:28:in `require'
	from /opt/metalware/src/domain_templates_renderer.rb:28:in `<top (required)>'
	from /opt/metalware/src/commands/remove/group.rb:26:in `require'
	from /opt/metalware/src/commands/remove/group.rb:26:in `<top (required)>'
	from /opt/metalware/src/commands.rb:29:in `require'
	from /opt/metalware/src/commands.rb:29:in `block in <top (required)>'
	from /opt/metalware/src/commands.rb:28:in `map'
	from /opt/metalware/src/commands.rb:28:in `<top (required)>'
	from /opt/metalware/src/cli_helper/parser.rb:26:in `require'
	from /opt/metalware/src/cli_helper/parser.rb:26:in `<top (required)>'
	from /opt/metalware/src/cli.rb:32:in `require'
	from /opt/metalware/src/cli.rb:32:in `<top (required)>'
	from bin/metal:26:in `require_relative'
	from bin/metal:26:in `<main>'
```

**Comment by bobwhitelock** [comment]
I can't reproduce this - I ran the following:

```sh
export alces_SOURCE_BRANCH=develop
export alces_OS=el7
curl -sL http://git.io/metalware-installer | /bin/bash
rm -rf /var/lib/metalware/repo/
metal repo use https://github.com/alces-software/metalware-default.git
```

and it appeared to work fine. Any other details which could be relevant? Were you installing on a machine which had previously had Metalware installed?

**Comment by ColonelPanicks** [comment]
Hmmm, that's rather strange! I had this with a freshly created VM, the commands I ran were:
```
curl -sL http://git.io/metalware-installer | alces_OS=el7 alces_SOURCE_BRANCH='feature/named' /bin/bash
echo "controller.testcluster.cluster.local" > /etc/hostname
init 6
metal repo use https://github.com/alces-software/metalware-default.git
```
I'm afraid I don't have the metalware-installer output. Will spin up another VM on this host when the one running on there is no longer in use and will retest.

**Comment by ColonelPanicks** [comment]
Have retested this again and hit no such issue, safe to ignore I think!

**Comment by bobwhitelock** [comment]
OK great, thanks for checking. I know what would cause that issue, but wouldn't expect it to be inconsistent so perhaps something went wrong in the install. In any case let me know if you see it again and I can investigate further/ give you a potential fix.
