### ISSUE TITLE
`method_missing` error when using `dns_type: named` (develop branch)

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#192]
This error appears at the end of any configure commands when the domain is set to use named instead of hosts. Output below (unrelated warnings have been snipped):
```
[root@controller repo]# metal configure self --trace
Root user encrypted password (1/15)  |$1$vHgqhJPA$R.jp2QQxR2fCCibtonWht0|

Kickstart template to use (2/15)  |default|

PXELINUX template to use (3/15)  |default|

Setup primary network (4/15) [yes/no]  |yes|

IP for nodes on the primary network (5/15)  |10.10.0.1|

Interface for the primary network (6/15)  |eth0|

Setup management network (7/15) [yes/no]  |yes|

IP for nodes on the management network (8/15)  |10.11.0.1|

Interface for the management network (9/15)  |eth1|

Setup BMC management network (10/15) [yes/no]  |no|

IP for nodes on the bmc network (11/15)  |10.11.<%= alces.group_index.to_i + 100%>.<%= alces.index %>|

Password for BMC device over LAN (12/15)  |Pa55Word|

Setup InfiniBand network (13/15) [yes/no]  |no|

IP for nodes on the InfiniBand network (14/15)  |10.12.<%= alces.group_index %>.<%= alces.index %>|

Interface for the InfiniBand network (15/15)  |ib0|

/opt/metalware/src/templating/missing_parameter_wrapper.rb:57:in `method_missing': 1..-1 is not a symbol nor a string (TypeError)
	from /opt/metalware/src/templating/missing_parameter_wrapper.rb:57:in `method_missing'
	from /opt/metalware/src/templating/missing_parameter_wrapper.rb:31:in `[]'
	from (erb):11:in `wrapper_binding'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:893:in `eval'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:893:in `block in result'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:894:in `result'
	from /opt/metalware/src/templating/renderer.rb:56:in `render_erb_template'
	from /opt/metalware/src/templating/renderer.rb:34:in `replace_erb'
	from /opt/metalware/src/templater.rb:178:in `replace_erb'
	from /opt/metalware/src/templater.rb:170:in `block in render'
	from /opt/metalware/src/templater.rb:169:in `open'
	from /opt/metalware/src/templater.rb:169:in `render'
	from /opt/metalware/src/templater.rb:63:in `render'
	from /opt/metalware/src/templater.rb:78:in `render_to_file'
	from /opt/metalware/src/dns/named.rb:111:in `render_zone_template'
	from /opt/metalware/src/dns/named.rb:44:in `block in update'
	from /opt/metalware/src/dns/named.rb:88:in `block in each_network'
	from /opt/metalware/src/templating/iterable_recursive_open_struct.rb:33:in `each'
	from /opt/metalware/src/templating/iterable_recursive_open_struct.rb:33:in `each'
	from /opt/metalware/src/dns/named.rb:88:in `each_network'
	from /opt/metalware/src/dns/named.rb:43:in `update'
	from /opt/metalware/src/domain_templates_renderer.rb:170:in `update_named'
	from /opt/metalware/src/domain_templates_renderer.rb:145:in `render_dns'
	from /opt/metalware/src/domain_templates_renderer.rb:43:in `block in render'
	from /opt/metalware/src/domain_templates_renderer.rb:42:in `each'
	from /opt/metalware/src/domain_templates_renderer.rb:42:in `render'
	from /opt/metalware/src/command_helpers/configure_command.rb:94:in `render_domain_templates'
	from /opt/metalware/src/command_helpers/configure_command.rb:47:in `run'
	from /opt/metalware/src/command_helpers/base_command.rb:40:in `initialize'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `new'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `call'
	from /opt/metalware/src/commander_extensions.rb:61:in `call'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:184:in `run'
	from /opt/metalware/src/commander_extensions.rb:49:in `run'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:464:in `run_active_command'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:66:in `run!'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/delegates.rb:15:in `run!'
	from /opt/metalware/src/cli.rb:52:in `run!'
	from /opt/metalware/src/cli.rb:47:in `run'
	from bin/metal:28:in `<main>'
```

**Comment by ColonelPanicks** [comment]
Further testing shows that the issue arises with the following line in `$repo/named/forward/default` :
```
@       IN MX   <%= alces.named.net.network.split(/\./).first %>  <%= alces.named.net.hostname[1..-1] %>.
```
It seems that the hostname method is no longer seen as a string or something funky is causing `[1..-1]` to be interpreted as a method call.

This can be fixed by changing the line to include `.to_s` after hostname:
```
@       IN MX   <%= alces.named.net.network.split(/\./).first %>  <%= alces.named.net.hostname.to_s[1..-1] %>.
```

If this is expected behaviour then I will make the above changes to `metalware-default`.

From putting the fix in place on a test system, this identified Issue #197
