### ISSUE TITLE
`metal configure self` uses node questions, not self

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#193]
When running `metal configure self` the questions which are asked are only those in the `nodes` namespace of `configure.yaml`.

Part of `configure.yaml`
```
node:
  root_password: *root_password

  kickstart_template: *kickstart_template
  pxelinux_template: *pxelinux_template

  pri_network_defined: *pri_network_defined
  pri_network_ip: *pri_network_ip
  pri_network_interface: *pri_network_interface

  mgt_network_defined: *mgt_network_defined
  mgt_network_ip: *mgt_network_ip
  mgt_network_interface: *mgt_network_interface

  bmc_network_defined: *bmc_network_defined
  bmc_network_ip: *bmc_network_ip
  bmc_password: *bmc_password

  ib_network_defined: *ib_network_defined
  ib_network_ip: *ib_network_ip
  ib_network_interface: *ib_network_interface

self:
  pri_network_defined: *pri_network_defined
  pri_network_ip: *pri_network_ip
  pri_network_short_hostname: *pri_network_short_hostname

  mgt_network_defined: *mgt_network_defined
  mgt_network_ip: *mgt_network_ip
  mgt_network_interface: *mgt_network_interface

  bmc_network_defined: *bmc_network_defined
  bmc_network_ip: *bmc_network_ip
  bmc_password: *bmc_password

  ib_network_defined: *ib_network_defined
  ib_network_ip: *ib_network_ip
  ib_network_interface: *ib_network_interface

  ext_network_defined: *ext_network_defined
  ext_network_domain: *ext_network_domain
  ext_network_ip: *ext_network_ip
  ext_network_network: *ext_network_network
  ext_network_netmask: *ext_network_netmask
  ext_network_interface: *ext_network_interface
  ext_network_gateway: *ext_network_gateway
```

Output from `metal configure self`:
```
[root@controller repo]# metal configure self
Root user encrypted password (1/15)  |$1$vHgqhJPA$R.jp2QQxR2fCCibtonWht0|

Kickstart template to use (2/15)  |default|

PXELINUX template to use (3/15)  |default|

Setup primary network (4/15) [yes/no]  |yes|

IP for nodes on the primary network (5/15)  |10.10.0.1|

Interface for the primary network (6/15)  |eth0|

Setup management network (7/15) [yes/no]  |yes|

IP for nodes on the management network (8/15)  |10.11.0.1|

Interface for the management network (9/15)  |eth1|

Setup BMC management network (10/15) [yes/no]  |no|

IP for nodes on the bmc network (11/15)  |10.11.<%= alces.group_index.to_i + 100%>.<%= alces.index %>|

Password for BMC device over LAN (12/15)  |Pa55Word|

Setup InfiniBand network (13/15) [yes/no]  |no|

IP for nodes on the InfiniBand network (14/15)  |10.12.<%= alces.group_index %>.<%= alces.index %>|

Interface for the InfiniBand network (15/15)  |ib0|

warning: Unset template parameter: send(answers).send(pri_network_defined)
warning: Unset template parameter: alces.answers.pri_network_defined
warning: Unset template parameter: send(answers).send(mgt_network_defined)
warning: Unset template parameter: alces.answers.mgt_network_defined
warning: Unset template parameter: send(answers).send(ib_network_defined)
warning: Unset template parameter: alces.answers.ib_network_defined
warning: Unset template parameter: send(answers).send(bmc_network_defined)
warning: Unset template parameter: alces.answers.bmc_network_defined
warning: Unset template parameter: send(answers).send(pri_network_defined)
warning: Unset template parameter: alces.answers.pri_network_defined
warning: Unset template parameter: send(answers).send(mgt_network_defined)
warning: Unset template parameter: alces.answers.mgt_network_defined
warning: Unset template parameter: send(answers).send(ib_network_defined)
warning: Unset template parameter: alces.answers.ib_network_defined
warning: Unset template parameter: send(answers).send(bmc_network_defined)
warning: Unset template parameter: alces.answers.bmc_network_defined
warning: Unset template parameter: send(answers).send(pri_network_defined)
warning: Unset template parameter: alces.answers.pri_network_defined
warning: Unset template parameter: send(answers).send(mgt_network_defined)
warning: Unset template parameter: alces.answers.mgt_network_defined
warning: Unset template parameter: send(answers).send(ib_network_defined)
warning: Unset template parameter: alces.answers.ib_network_defined
warning: Unset template parameter: send(answers).send(bmc_network_defined)
warning: Unset template parameter: alces.answers.bmc_network_defined
warning: Unset template parameter: send(answers).send(pri_network_defined)
warning: Unset template parameter: alces.answers.pri_network_defined
warning: Unset template parameter: send(answers).send(mgt_network_defined)
warning: Unset template parameter: alces.answers.mgt_network_defined
warning: Unset template parameter: send(answers).send(ib_network_defined)
warning: Unset template parameter: alces.answers.ib_network_defined
warning: Unset template parameter: send(answers).send(bmc_network_defined)
warning: Unset template parameter: alces.answers.bmc_network_defined
```

**Comment by ColonelPanicks** [comment]
### Using development branch, 2017.1.0-rc1 tag

Unsure if this issue persists due to running `metal configure self` throwing out the following error:
```
[root@localhost repo]# metal configure self --trace
/opt/metalware/src/command_helpers/configure_command.rb:62:in `answer_file': NotImplementedError (NotImplementedError)
	from /opt/metalware/src/command_helpers/configure_command.rb:66:in `relative_answer_file'
	from /opt/metalware/src/command_helpers/configure_command.rb:73:in `dependency_hash'
	from /opt/metalware/src/command_helpers/base_command.rb:79:in `enforce_dependency'
	from /opt/metalware/src/command_helpers/base_command.rb:59:in `post_setup'
	from /opt/metalware/src/command_helpers/base_command.rb:39:in `initialize'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `new'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `call'
	from /opt/metalware/src/commander_extensions.rb:61:in `call'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:184:in `run'
	from /opt/metalware/src/commander_extensions.rb:49:in `run'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:464:in `run_active_command'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:66:in `run!'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/delegates.rb:15:in `run!'
	from /opt/metalware/src/cli.rb:52:in `run!'
	from /opt/metalware/src/cli.rb:47:in `run'
	from bin/metal:28:in `<main>'
```

I attempted to fix this by removing the `self:` section entirely from `configure.yaml` but the problem persists.
