### ISSUE TITLE
Unset template parameter when building self (`fix/various-bugs` branch)

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#200]
Attempting to build self errors with unset template parameters despite `metal configure self` having been run through and answers existing in `answers/self.yaml`
```
[root@localhost ~]# metal build self
error: Unset template parameter: send(send,pri_network_defined). Use --trace to view backtrace
[root@localhost ~]# metal build self --trace
/opt/metalware/src/templating/missing_parameter_wrapper.rb:60:in `method_missing': Unset template parameter: send(send,pri_network_defined) (Metalware::MissingParameterError)
	from /opt/metalware/src/templating/missing_parameter_wrapper.rb:57:in `method_missing'
	from /opt/metalware/src/templating/missing_parameter_wrapper.rb:57:in `method_missing'
	from (erb):1:in `wrapper_binding'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:893:in `eval'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:893:in `block in result'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:894:in `result'
	from /opt/metalware/src/templating/renderer.rb:56:in `render_erb_template'
	from /opt/metalware/src/templating/renderer.rb:34:in `replace_erb'
	from /opt/metalware/src/templating/repo_config_parser.rb:132:in `parse_string_config_value'
	from /opt/metalware/src/templating/repo_config_parser.rb:120:in `parse_config_value'
	from /opt/metalware/src/templating/repo_config_parser.rb:123:in `block in parse_config_value'
	from /opt/metalware/src/templating/repo_config_parser.rb:122:in `each'
	from /opt/metalware/src/templating/repo_config_parser.rb:122:in `map'
	from /opt/metalware/src/templating/repo_config_parser.rb:122:in `parse_config_value'
	from /opt/metalware/src/templating/repo_config_parser.rb:123:in `block in parse_config_value'
	from /opt/metalware/src/templating/repo_config_parser.rb:122:in `each'
	from /opt/metalware/src/templating/repo_config_parser.rb:122:in `map'
	from /opt/metalware/src/templating/repo_config_parser.rb:122:in `parse_config_value'
	from /opt/metalware/src/templating/repo_config_parser.rb:113:in `block in perform_config_parsing_pass'
	from /opt/metalware/src/templating/repo_config_parser.rb:112:in `each'
	from /opt/metalware/src/templating/repo_config_parser.rb:112:in `map'
	from /opt/metalware/src/templating/repo_config_parser.rb:112:in `perform_config_parsing_pass'
	from /opt/metalware/src/templating/repo_config_parser.rb:56:in `parse'
	from /opt/metalware/src/templating/repo_config_parser.rb:36:in `parse_for_node'
	from /opt/metalware/src/templater.rb:161:in `initialize'
	from /opt/metalware/src/node.rb:137:in `new'
	from /opt/metalware/src/node.rb:137:in `repo_config'
	from /opt/metalware/src/node.rb:213:in `repo_build_method'
	from /opt/metalware/src/node.rb:204:in `validate_build_method'
	from /opt/metalware/src/node.rb:188:in `build_method_class'
	from /opt/metalware/src/node.rb:184:in `build_method'
	from /opt/metalware/src/node.rb:141:in `build_template_paths'
	from /opt/metalware/src/nodes.rb:37:in `each'
	from /opt/metalware/src/nodes.rb:37:in `each'
	from /opt/metalware/src/commands/build.rb:83:in `map'
	from /opt/metalware/src/commands/build.rb:83:in `repo_dependencies'
	from /opt/metalware/src/commands/build.rb:74:in `dependency_hash'
	from /opt/metalware/src/command_helpers/base_command.rb:79:in `enforce_dependency'
	from /opt/metalware/src/command_helpers/base_command.rb:59:in `post_setup'
	from /opt/metalware/src/command_helpers/base_command.rb:39:in `initialize'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `new'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `call'
	from /opt/metalware/src/commander_extensions.rb:61:in `call'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:184:in `run'
	from /opt/metalware/src/commander_extensions.rb:49:in `run'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:464:in `run_active_command'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:66:in `run!'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/delegates.rb:15:in `run!'
	from /opt/metalware/src/cli.rb:52:in `run!'
	from /opt/metalware/src/cli.rb:47:in `run'
	from bin/metal:28:in `<main>'
[root@localhost repo]# cat ../answers/self.yaml
---
pri_network_defined: true
pri_network_ip: 10.10.0.1
mgt_network_defined: true
mgt_network_ip: 10.11.0.1
bmc_network_defined: false
ib_network_defined: false
ext_network_defined: true
ext_network_ip: 10.101.100.25
ext_network_gateway: 10.101.0.1
```

**Comment by ColonelPanicks** [comment]
Creating a copy of `answers/self.yaml` to `answers/nodes/self.yaml` fixes this issue.

Should self be considered a node or stay outside? 🤔 Doesn't seem like too much of a worry but needs to be straightened out one way or another!
