### ISSUE TITLE
Uninformative error when attempt to build undefined node

### ISSUE THREAD

**Issue by bobwhitelock** [alces-software/metalware#210]
```
[root@controller(dev) metalware]# bin/metal build node01 --trace
/tmp/metalware/src/templating/missing_parameter_wrapper.rb:37:in `method_missing': Unset template parameter: send(send,cluster_name) (Metalware::MissingParameterError)
        from /tmp/metalware/src/templating/missing_parameter_wrapper.rb:34:in `method_missing'
        from /tmp/metalware/src/templating/missing_parameter_wrapper.rb:34:in `method_missing'
        from (erb):1:in `wrapper_binding'
```

As discussed from https://alces.slack.com/archives/C5FL99R89/p1506338942000187.

**Comment by WilliamMcCumstie** [comment]
`send` methods should be converted to `cluster_name`
And hash indexing should be converted from [](key) to [:key]
