### ISSUE TITLE
`metal view-config` no longer works

### ISSUE THREAD

**Issue by bobwhitelock** [alces-software/metalware#211]
With no answer files yet the following error is given:

```
[root@controller(dev) metalware]# bin/metal view-config --trace
warning: Unset template parameter: send(answers).send(cluster_name)
warning: Unset template parameter: alces.answers.cluster_name
warning: Unset template parameter: send(answers).send(root_password)
warning: Unset template parameter: alces.answers.root_password
warning: Unset template parameter: send(answers).send(root_ssh_key)
warning: Unset template parameter: alces.answers.root_ssh_key
warning: Unset template parameter: send(answers).send(externaldns)
warning: Unset template parameter: alces.answers.externaldns
warning: Unset template parameter: send(answers).send(pri_network_defined)
warning: Unset template parameter: alces.answers.pri_network_defined
warning: Unset template parameter: send(answers).send(mgt_network_defined)
warning: Unset template parameter: alces.answers.mgt_network_defined
warning: Unset template parameter: send(answers).send(ib_network_defined)
warning: Unset template parameter: alces.answers.ib_network_defined
warning: Unset template parameter: send(answers).send(bmc_network_defined)
warning: Unset template parameter: alces.answers.bmc_network_defined
/tmp/metalware/src/templating/magic_namespace.rb:111:in `method_missing': wrong number of arguments (given 0, expected 1+) (ArgumentError)
        from /tmp/metalware/src/object_fields_hasher.rb:12:in `block in hash_object'
        from /tmp/metalware/src/object_fields_hasher.rb:10:in `map'
        from /tmp/metalware/src/object_fields_hasher.rb:10:in `hash_object'
        from /tmp/metalware/src/templating/magic_namespace.rb:42:in `to_h'
        from /tmp/metalware/src/templating/magic_namespace.rb:39:in `to_json'
        from /tmp/metalware/src/templating/missing_parameter_wrapper.rb:11:in `to_json'
        from /tmp/metalware/src/templating/iterable_recursive_open_struct.rb:30:in `to_json'
        from /tmp/metalware/src/templating/iterable_recursive_open_struct.rb:30:in `to_json'
        from /tmp/metalware/src/templating/missing_parameter_wrapper.rb:11:in `to_json'
        from /tmp/metalware/src/commands/view_config.rb:36:in `templating_config_json'
        from /tmp/metalware/src/commands/view_config.rb:18:in `run'
        from /tmp/metalware/src/command_helpers/base_command.rb:40:in `initialize'
        from /usr/local/rvm/gems/ruby-2.4.1/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `new'
        from /usr/local/rvm/gems/ruby-2.4.1/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `call'
        from /tmp/metalware/src/commander_extensions.rb:61:in `call'
        from /usr/local/rvm/gems/ruby-2.4.1/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:184:in `run'
        from /tmp/metalware/src/commander_extensions.rb:49:in `run'
        from /usr/local/rvm/gems/ruby-2.4.1/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:464:in `run_active_command'
        from /usr/local/rvm/gems/ruby-2.4.1/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:66:in `run!'
        from /usr/local/rvm/gems/ruby-2.4.1/bundler/gems/commander-c99203ec5a74/lib/commander/delegates.rb:15:in `run!'
        from /tmp/metalware/src/cli.rb:52:in `run!'
        from /tmp/metalware/src/cli.rb:47:in `run'
        from bin/metal:28:in `<main>'
```

**Comment by WilliamMcCumstie** [comment]
It looks like somewhere along the way send(:method_missing) is being called. It is likely the `object_field_hasher` interacting with the updated `MissingParameterWrapper`.

Investigating now.
