### ISSUE TITLE
`--answers` validation errors despite valid information being supplied

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#217]
I attempted to run a known-working (Issue #194) metal configure command using the answers arg:
```
[root@controller repo]# metal configure domain -a '{"cluster_name": "test"}'
```
And was met with the following:
```
error: Failed to validate answers:
The following question(s) were detected in the answer file but do not appear in 'configure.yaml': cluster_name. Use --trace to view backtrace
```
Trace:
```
/opt/metalware/src/validation/answer.rb:78:in `data': Failed to validate answers: (Metalware::ValidationFailure)
The following question(s) were detected in the answer file but do not appear in 'configure.yaml': cluster_name
	from /opt/metalware/src/validation/saver.rb:73:in `answer'
	from /opt/metalware/src/validation/load_save_base.rb:38:in `domain_answers'
	from /opt/metalware/src/validation/load_save_base.rb:56:in `section_answers'
	from /opt/metalware/src/validation/saver.rb:46:in `method_missing'
	from /opt/metalware/src/configurator.rb:170:in `save_answers'
	from /opt/metalware/src/configurator.rb:91:in `configure'
	from /opt/metalware/src/command_helpers/configure_command.rb:43:in `run'
	from /opt/metalware/src/command_helpers/base_command.rb:40:in `initialize'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `new'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `call'
	from /opt/metalware/src/commander_extensions.rb:61:in `call'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:184:in `run'
	from /opt/metalware/src/commander_extensions.rb:49:in `run'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:464:in `run_active_command'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:66:in `run!'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/delegates.rb:15:in `run!'
	from /opt/metalware/src/cli.rb:52:in `run!'
	from /opt/metalware/src/cli.rb:47:in `run'
	from bin/metal:28:in `<main>'
```

**Comment by WilliamMcCumstie** [comment]
The bug is being caused by the answer hash containing keys in string notation. So "cluster_name" is not a valid key as it does not appear in `configure.yaml`. However `:cluster_name` is a valid key as it is a symbol.

Should be a fairly easy fix to convert the answer hash into symbols
