### ISSUE TITLE
[2017.2.0-pre5] Repo Use Error

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#246]
When I try to use the repo I see the following:
```[root@localhost ~]# metal repo use https://github.com/alces-software/metalware-default.git
/opt/metalware/src/deployment_server.rb:59:in `build_interface': uninitialized constant #<Class:Metalware::DeploymentServer>::Network (NameError)
	from /opt/metalware/src/cli_helper/dynamic_defaults.rb:8:in `build_interface'
	from /opt/metalware/src/cli_helper/parser.rb:93:in `parse_default'
	from /opt/metalware/src/cli_helper/parser.rb:70:in `block (3 levels) in parse_command_attributes'
	from /opt/metalware/src/cli_helper/parser.rb:64:in `each'
	from /opt/metalware/src/cli_helper/parser.rb:64:in `block (2 levels) in parse_command_attributes'
	from /opt/metalware/src/cli_helper/parser.rb:59:in `each'
	from /opt/metalware/src/cli_helper/parser.rb:59:in `block in parse_command_attributes'
	from /opt/metalware/src/commander_extensions.rb:42:in `command'
	from /opt/metalware/src/cli_helper/parser.rb:58:in `parse_command_attributes'
	from /opt/metalware/src/cli_helper/parser.rb:47:in `block in parse_commands'
	from /opt/metalware/src/cli_helper/parser.rb:46:in `each'
	from /opt/metalware/src/cli_helper/parser.rb:46:in `parse_commands'
	from /opt/metalware/src/cli.rb:45:in `run'
	from bin/metal:28:in `<main>'```

**Comment by ColonelPanicks** [comment]
If I try to workaround by creating `/var/lib/metalware/repo/server.yaml` then I don't hit the build interface error but instead hit the expected "Repository already exists" error. 

For now my workaround is to just manually clone the repository and go from there.

**Comment by WilliamMcCumstie** [comment]
From the looks of it, when `DeploymentServer` falls back on `Networks.interfaces.first` there is an error. When `server.yaml` is specified, there isn't an issue as the code isn't reached.

As it is a `NameError`, its likely that `Networks` isn't being required
