### ISSUE TITLE
[2017.2.0-rc1] Cancelling Build Fails to Run Build Hooks

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#253]
When running `metal build node01`, I cancelled it when it was hanging waiting for nodes to build, after answering 'yes' to "Run the complete_hook for nodes as if build succeeded" I see the following:
```
[root@controller 7]# metal build node01 --trace
Waiting for nodes to report as built...
(Ctrl-C to terminate)
^CExiting...
Run the complete_hook for nodes as if build succeeded?
[yes/no]
yes
/opt/metalware/src/commands/build.rb:153:in `ask_if_should_run_build_complete': undefined local variable or method `run_all_complete_hooks' for #<Metalware::Commands::Build:0x00000002fb0318> (NameError)
	from /opt/metalware/src/commands/build.rb:132:in `handle_interrupt'
	from /opt/metalware/src/command_helpers/base_command.rb:43:in `rescue in initialize'
	from /opt/metalware/src/command_helpers/base_command.rb:38:in `initialize'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `new'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `call'
	from /opt/metalware/src/commander_extensions.rb:61:in `call'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:184:in `run'
	from /opt/metalware/src/commander_extensions.rb:49:in `run'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:464:in `run_active_command'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:66:in `run!'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/delegates.rb:15:in `run!'
	from /opt/metalware/src/cli.rb:52:in `run!'
	from /opt/metalware/src/cli.rb:47:in `run'
	from bin/metal:28:in `<main>'
```

**Comment by ColonelPanicks** [comment]
Additionally, the build complete hooks are not run (or firstboot isn't toggled) meaning that once the build has complete the node starts building again
