### ISSUE TITLE
[2017.2.0-rc2] Named Templates Fail to Render

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#263]
When templating for the local node (using `named` as the DNS type), the following is seen:
```
[root@localhost repo]# metal template local
warning: Build file: Template path '/opt/alces/install/scripts/aws.sh' for '/opt/alces/install/scripts/aws.sh' does not exist
warning: The following returned nil: answer.pri_network_defined
warning: The following returned nil: answer.mgt_network_defined
warning: The following returned nil: answer.ib_network_defined
warning: The following returned nil: answer.bmc_network_defined
error: Failed to render template: /var/lib/metalware/repo/named/forward/default
Error, a Node is not in scope. Use --trace to view backtrace
```

Trace:
```
[root@localhost repo]# metal template local --trace
warning: Build file: Template path '/opt/alces/install/scripts/aws.sh' for '/opt/alces/install/scripts/aws.sh' does not exist
warning: The following returned nil: answer.pri_network_defined
warning: The following returned nil: answer.mgt_network_defined
warning: The following returned nil: answer.ib_network_defined
warning: The following returned nil: answer.bmc_network_defined
/opt/metalware/src/namespaces/alces.rb:57:in `node': Failed to render template: /var/lib/metalware/repo/named/forward/default (Metalware::ScopeError)
Error, a Node is not in scope
	from /opt/metalware/src/templating/nil_detection_wrapper.rb:35:in `method_missing'
	from (erb):1:in `alces_wrapper_binding'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:893:in `eval'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:893:in `block in result'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:894:in `result'
	from /opt/metalware/src/templating/renderer.rb:62:in `render_erb_template'
	from /opt/metalware/src/templating/renderer.rb:40:in `replace_erb_with_binding'
	from /opt/metalware/src/namespaces/alces.rb:85:in `block in render_erb_template'
	from /opt/metalware/src/namespaces/alces.rb:121:in `run_with_dynamic'
	from /opt/metalware/src/namespaces/alces.rb:83:in `render_erb_template'
	from /opt/metalware/src/namespaces/hash_merger_namespace.rb:54:in `block in template_block'
	from /opt/metalware/src/hash_mergers/metal_recursive_open_struct.rb:49:in `convert_value'
	from /opt/metalware/src/hash_mergers/metal_recursive_open_struct.rb:31:in `[]'
	from /opt/metalware/src/hash_mergers/metal_recursive_open_struct.rb:20:in `method_missing'
	from /opt/metalware/src/templating/nil_detection_wrapper.rb:35:in `method_missing'
	from (erb):1:in `alces_wrapper_binding'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:893:in `eval'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:893:in `block in result'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:894:in `result'
	from /opt/metalware/src/templating/renderer.rb:62:in `render_erb_template'
	from /opt/metalware/src/templating/renderer.rb:40:in `replace_erb_with_binding'
	from /opt/metalware/src/namespaces/alces.rb:85:in `block in render_erb_template'
	from /opt/metalware/src/namespaces/alces.rb:121:in `run_with_dynamic'
	from /opt/metalware/src/namespaces/alces.rb:83:in `render_erb_template'
	from /opt/metalware/src/namespaces/hash_merger_namespace.rb:54:in `block in template_block'
	from /opt/metalware/src/hash_mergers/metal_recursive_open_struct.rb:49:in `convert_value'
	from /opt/metalware/src/hash_mergers/metal_recursive_open_struct.rb:31:in `[]'
	from /opt/metalware/src/hash_mergers/metal_recursive_open_struct.rb:20:in `method_missing'
	from /opt/metalware/src/templating/nil_detection_wrapper.rb:35:in `method_missing'
	from (erb):11:in `alces_wrapper_binding'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:893:in `eval'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:893:in `block in result'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:894:in `result'
	from /opt/metalware/src/templating/renderer.rb:62:in `render_erb_template'
	from /opt/metalware/src/templating/renderer.rb:40:in `replace_erb_with_binding'
	from /opt/metalware/src/namespaces/alces.rb:85:in `block in render_erb_template'
	from /opt/metalware/src/namespaces/alces.rb:121:in `run_with_dynamic'
	from /opt/metalware/src/namespaces/alces.rb:83:in `render_erb_template'
	from /opt/metalware/src/templater.rb:63:in `render'
	from /opt/metalware/src/templater.rb:172:in `render'
	from /opt/metalware/src/dns/named.rb:88:in `render_zone_template'
	from /opt/metalware/src/dns/named.rb:49:in `block in update'
	from /opt/metalware/src/dns/named.rb:67:in `block in each_network'
	from /opt/metalware/src/hash_mergers/metal_recursive_open_struct.rb:35:in `block in each'
	from /opt/metalware/src/hash_mergers/metal_recursive_open_struct.rb:35:in `each'
	from /opt/metalware/src/hash_mergers/metal_recursive_open_struct.rb:35:in `each'
	from /opt/metalware/src/dns/named.rb:67:in `each_network'
	from /opt/metalware/src/dns/named.rb:48:in `update'
	from /opt/metalware/src/commands/template.rb:49:in `block in run'
	from /opt/metalware/src/staging.rb:21:in `block in template'
	from /opt/metalware/src/staging.rb:14:in `update'
	from /opt/metalware/src/staging.rb:20:in `template'
	from /opt/metalware/src/commands/template.rb:45:in `run'
	from /opt/metalware/src/command_helpers/base_command.rb:41:in `initialize'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `new'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `call'
	from /opt/metalware/src/commander_extensions.rb:61:in `call'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:184:in `run'
	from /opt/metalware/src/commander_extensions.rb:49:in `run'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:464:in `run_active_command'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:66:in `run!'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/delegates.rb:15:in `run!'
	from /opt/metalware/src/cli.rb:52:in `run!'
	from /opt/metalware/src/cli.rb:47:in `run'
	from bin/metal:28:in `<main>'
```

The `alces.named` namespace cannot be accessed out side of metalware's internal stuff but if I take a copy of [`/var/lib/metalware/repo/named/forward/default`](https://github.com/alces-software/metalware-default/blob/release/2017.2/named/forward/default) and remove any lines using this namespace then I am able to `metal render` it on the command line without issue.

**Comment by WilliamMcCumstie** [comment]
This isn't a bug in metalware.

The `named` template is always rendered in a domain scope. This means well the following line of code is rendered in the `named/forward/default` template:
```
@       IN MX   <%= alces.named.net.network.split(/\./).first %>  <%= alces.named.net.hostname[1..-1] %>.
```

The `alces.named.net.hostname` will refer to `domain.yaml` and renders:
```
<%= config.networks.pri.short_hostname %>.<%= config.domain %>
```

The `config.networks.pri.short_hostname` will refer to `domain.yaml` again and renders:
```
<%= node.name %>.<%= config.networks.pri.domain %>
```

However `node.name` can not be rendered as it is not in scope. As far as I can tell `metalware` is behaving correctly. This bug should be fixed in `metalware-default`.
