### ISSUE TITLE
Node not in scope when configuring

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#347]
`metal configure local` outputs this at the end of configure
```
/opt/metalware/src/namespaces/alces.rb:55:in `node': Error, a Node is not in scope (Metalware::ScopeError)
	from /opt/metalware/src/templating/nil_detection_wrapper.rb:34:in `method_missing'
	from (erb):1:in `alces_wrapper_binding'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:893:in `eval'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:893:in `block in result'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:894:in `result'
	from /opt/metalware/src/templating/renderer.rb:62:in `render_erb_template'
	from /opt/metalware/src/templating/renderer.rb:40:in `replace_erb_with_binding'
	from /opt/metalware/src/namespaces/alces.rb:73:in `block in render_erb_template'
	from /opt/metalware/src/namespaces/alces.rb:105:in `run_with_dynamic'
	from /opt/metalware/src/namespaces/alces.rb:71:in `render_erb_template'
	from /opt/metalware/src/namespaces/hash_merger_namespace.rb:57:in `block in template_block'
	from /opt/metalware/src/hash_mergers/metal_recursive_open_struct.rb:49:in `convert_value'
	from /opt/metalware/src/hash_mergers/metal_recursive_open_struct.rb:31:in `[]'
	from /opt/metalware/src/configurator.rb:126:in `block in reject_non_saved_answers'
	from /opt/metalware/src/configurator.rb:125:in `reject'
	from /opt/metalware/src/configurator.rb:125:in `reject_non_saved_answers'
	from /opt/metalware/src/configurator.rb:120:in `save_answers'
	from /opt/metalware/src/configurator.rb:90:in `block in configure'
	from /opt/metalware/src/group_cache.rb:34:in `update'
	from /opt/metalware/src/configurator.rb:87:in `configure'
	from /opt/metalware/src/command_helpers/configure_command.rb:44:in `run'
	from /opt/metalware/src/command_helpers/base_command.rb:40:in `initialize'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-71bcf5dd108e/lib/commander/command.rb:217:in `new'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-71bcf5dd108e/lib/commander/command.rb:217:in `call'
	from /opt/metalware/src/commander_extensions.rb:61:in `call'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-71bcf5dd108e/lib/commander/command.rb:184:in `run'
	from /opt/metalware/src/commander_extensions.rb:49:in `run'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-71bcf5dd108e/lib/commander/runner.rb:477:in `run_active_command'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-71bcf5dd108e/lib/commander/runner.rb:66:in `run!'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-71bcf5dd108e/lib/commander/delegates.rb:16:in `run!'
	from /opt/metalware/src/cli.rb:55:in `run!'
	from /opt/metalware/src/cli.rb:50:in `run'
	from bin/metal:28:in `<main>'
```

**Comment by WilliamMcCumstie** [comment]
Turns out the higher level answers are being rendered before the save comparison occurs. The un-rendered answer should be used for this comparison. The `node` not in scope is just a side affect of the underling bug.

It has been fixed by ensuring the un-rendered version is used.
